version: '2'
services:
  debug:
    image: yaohaitao/php-71-apache-xdebug-intl
    ports:
     - "8081:80"
    volumes:
      - ./:/var/www/html
    environment:
        #TODO
        #change the line below with your IP address that is visible from Docker
        XDEBUG_CONFIG: remote_host=XXX.XXX.XXX.XXX